### ISSUE TITLE
Error ``<!DOCTYPE html>``

### ISSUE THREAD

**Issue by vilinski** [CodeZombieCH/vscode-gitignore#2] opened 2016-08-11 13:41 UTC
Command "Add gitignore" does nothing and emits an error with this text `<!DOCTYPE html>`

Environment:
Windows 7 with firewall
VSC 1.4.0
CodeZombie.gitignore 0.2.0
michelemelluse.gitignore 1.0.1

**Comment by CodeZombieCH** [comment] 2016-09-26 18:06
Are you using a proxy?

**Comment by CodeZombieCH** [comment] 2016-12-04 20:38
I assume this was caused by a proxy.
Resolved by #1 in Version 0.5.0

**Closed by CodeZombieCH** 2016-12-04 20:38 UTC

**Comment by vilinski** [comment] 2016-12-06 22:01
yes it was proxy, thank you for fix
