### ISSUE TITLE
Extension not usable due to rate limit

### ISSUE THREAD

**Issue by rlivings39** [CodeZombieCH/vscode-gitignore#19] opened 2019-09-17 18:15 UTC
When I try to add a gitignore I get the error:

```
403: {"message":"API rate limit exceeded for 144.212.128.4. (But here's the good news: 
Authenticated requests get a higher rate limit. Check out the documentation for more 
details.)","documentation_url":"https://developer.github.com/v3/#rate-limiting"}
```

This has been happening for the past few days without fail.

**Comment by tyler-8** [comment] 2019-10-01 18:44
Same problem from https://github.com/CodeZombieCH/vscode-gitignore/issues/18.

**Comment by jimmyharris** [comment] 2021-02-11 15:35
Can we please add token authentication for the github API?

**Comment by CodeZombieCH** [comment] 2021-05-12 21:31
Duplicate of #18.

**Closed by CodeZombieCH** 2021-05-12 21:31 UTC
